
export const createOption = (label) => ({
  label,
  value: label.toLowerCase().replace(/\W/g, ""),
});
export const groupStyles = {
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
};
export const groupBadgeStyles = {
  backgroundColor: "#EBECF0",
  borderRadius: "2em",
  color: "#172B4D",
  display: "inline-block",
  fontSize: 12,
  fontWeight: "normal",
  lineHeight: "1",
  minWidth: 1,
  padding: "0.16666666666667em 0.5em",
  textAlign: "center",
};

export const formatGroupLabel = (data) => (
  <div style={groupStyles}>
    <span>{data.label}</span>
    <span style={groupBadgeStyles}>{data.options.length}</span>
  </div>
);

export  const formatLatLong = (latLang) => {
    if (latLang && latLang.latitude && latLang.longitude) {
      return `${latLang.latitude},${latLang.longitude}`;
    }
    return "";
  };


const topsOptions = [
  createOption("T-shirt"),
  createOption("Long sleeved"),
  createOption("Blouse"),
  createOption("Collared shirt"),
  createOption("Button up"),
  createOption("Cardigan"),
  createOption("Knit sweater"),
  createOption("Tank top"),
  createOption("Hoodie"),
  createOption("Polo shirt"),
  createOption("Crop top"),
  createOption("Tunic"),
  createOption("Wrap top"),
  createOption("Peplum top"),
  createOption("Off-shoulder top"),
  createOption("Bodysuit"),
  createOption("Sleeveless blouse"),
  createOption("Dress"),
  createOption("Sweater"),
  createOption("Sweatshirt"),
  createOption("Turtleneck"),
  createOption("Jumper"),
  createOption("Blazer"),

];

const bottomsOptions = [
  createOption("Jeans"),
  createOption("Slacks"),
  createOption("Shorts"),
  createOption("Skirt, long"),
  createOption("Skirt, short"),
  createOption("Leggings"),
  createOption("Sweatpants"),
  createOption("Cargo pants"),
  createOption("Culottes"),
  createOption("Palazzo pants"),
  createOption("Pencil skirt"),
  createOption("A-line skirt"),
  createOption("Denim skirt"),
  createOption("High-waisted shorts"),
  createOption("Flared pants"),
  createOption("Pants"),

];

const shoesOptions = [
  createOption("Sneakers"),
  createOption("Sandals"),
  createOption("Boots"),
  createOption("Flats"),
  createOption("Heels"),
  createOption("Loafers"),
  createOption("Oxfords"),
  createOption("Espadrilles"),
  createOption("Mules"),
  createOption("Platform shoes"),
  createOption("Wedges"),
];

const outerwearOptions = [
  createOption("Puffer jacket"),
  createOption("Vest"),
  createOption("Trenchcoat"),
  createOption("Jean Jacket"),
  createOption("Leather jacket"),
  createOption("Raincoat"),
  createOption("Peacoat"),
  createOption("Fitted jacket"),
  createOption("Parka"),
  createOption("Windbreaker"),
  createOption("Bomber jacket"),
  createOption("Quilted jacket"),
  createOption("Fur coat"),
  createOption("Cape"),
  createOption("Shawl"),
  createOption("Kimono"),
  createOption("Poncho"),
];

const accessoriesOptions = [
  createOption("Baseball cap"),
  createOption("Beanie"),
  createOption("Hat, other"),
  createOption("Scarf, knit"),
  createOption("Scarf, silk"),
  createOption("Tote bag"),
  createOption("Handbag"),
  createOption("Backpack"),
  createOption("Crossbody bag"),
  createOption("Sunglasses"),
  createOption("Bracelet"),
  createOption("Earrings"),
  createOption("Necklace"),
  createOption("Ring"),
  createOption("Watch"),
  createOption("Belt"),
  createOption("Gloves"),
  createOption("Headband"),
  createOption("Choker"),
];

export const groupedOptions = [
  {
    label: "TOPS",
    options: topsOptions,
  },
  {
    label: "BOTTOMS",
    options: bottomsOptions,
  },
  {
    label: "SHOES",
    options: shoesOptions,
  },
  {
    label: "OUTERWEAR",
    options: outerwearOptions,
  },
  {
    label: "ACCESSORIES",
    options: accessoriesOptions,
  },
];

export const colors = [
  createOption("Alice Blue"),
  createOption("Amaranth"),
  createOption("Amethyst"),
  createOption("Aquamarine"),
  createOption("Azure"),
  createOption("Beige"),
  createOption("Bisque"),
  createOption("Black"),
  createOption("Blue"),
  createOption("Bronze"),
  createOption("Brown"),
  createOption("Burgundy"),
  createOption("Burnt Sienna"),
  createOption("Byzantium"),
  createOption("Celadon"),
  createOption("Cerulean"),
  createOption("Cerulean Blue"),
  createOption("Champagne"),
  createOption("Chartreuse"),
  createOption("Chocolate"),
  createOption("Cobalt"),
  createOption("Coral"),
  createOption("Coral Pink"),
  createOption("Cornflower"),
  createOption("Cornsilk"),
  createOption("Crimson"),
  createOption("Crimson Red"),
  createOption("Cyan"),
  createOption("Dark Goldenrod"),
  createOption("Dark Green"),
  createOption("Dark Olive Green"),
  createOption("Dark Salmon"),
  createOption("Dark Slate Gray"),
  createOption("Deep Pink"),
  createOption("Deep Purple"),
  createOption("Deep Sky Blue"),
  createOption("Denim"),
  createOption("Eggplant"),
  createOption("Eggshell"),
  createOption("Emerald"),
  createOption("Firebrick"),
  createOption("Forest Green"),
  createOption("Fuchsia"),
  createOption("Gold"),
  createOption("Golden Yellow"),
  createOption("Goldenrod"),
  createOption("Gray"),
  createOption("Green"),
  createOption("Honeydew"),
  createOption("Hot Pink"),
  createOption("Iris"),
  createOption("Ivory"),
  createOption("Jade"),
  createOption("Jasmine"),
  createOption("Khaki"),
  createOption("Lavender"),
  createOption("Lavender Blush"),
  createOption("Lavender Gray"),
  createOption("Lemon"),
  createOption("Light Blue"),
  createOption("Light Coral"),
  createOption("Light Green"),
  createOption("Light Pink"),
  createOption("Light Slate Gray"),
  createOption("Lime"),
  createOption("Magenta"),
  createOption("Magenta Pink"),
  createOption("Magenta Rose"),
  createOption("Maroon"),
  createOption("Mauve"),
  createOption("Mauve Taupe"),
  createOption("Medium Purple"),
  createOption("Medium Spring Green"),
  createOption("Medium Turquoise"),
  createOption("Medium Violet Red"),
  createOption("Midnight Blue"),
  createOption("Mint"),
  createOption("Mulberry"),
  createOption("Mustard"),
  createOption("Navy"),
  createOption("Navajo White"),
  createOption("Neon Green"),
  createOption("Ocean Blue"),
  createOption("Olive"),
  createOption("Olive Drab"),
  createOption("Orange"),
  createOption("Orchid"),
  createOption("Pale Goldenrod"),
  createOption("Pale Green"),
  createOption("Pale Pink"),
  createOption("Pale Turquoise"),
  createOption("Papaya Whip"),
  createOption("Peach"),
  createOption("Peach Puff"),
  createOption("Pear"),
  createOption("Pearl"),
  createOption("Periwinkle"),
  createOption("Pink"),
  createOption("Platinum"),
  createOption("Plum"),
  createOption("Poppy Red"),
  createOption("Powder Blue"),
  createOption("Powder Pink"),
  createOption("Purple"),
  createOption("Raspberry"),
  createOption("Red"),
  createOption("Rose"),
  createOption("Royal Blue"),
  createOption("Ruby"),
  createOption("Sage Green"),
  createOption("Salmon"),
  createOption("Sangria"),
  createOption("Sapphire"),
  createOption("Scarlet"),
  createOption("Sea Green"),
  createOption("Seafoam Green"),
  createOption("Sienna"),
  createOption("Silver"),
  createOption("Slate"),
  createOption("Slate Gray"),
  createOption("Spring Green"),
  createOption("Steel Blue"),
  createOption("Sunflower Yellow"),
  createOption("Tan"),
  createOption("Tangerine"),
  createOption("Taupe"),
  createOption("Teal"),
  createOption("Terra Cotta"),
  createOption("Thistle"),
  createOption("Tomato"),
  createOption("Turquoise"),
  createOption("Ultramarine"),
  createOption("Vanilla"),
  createOption("Violet"),
  createOption("Viridian"),
  createOption("Wine"),
  createOption("Wine Red"),
  createOption("White"),
  createOption("Yellow"),

  createOption("Zaffre"),
];
