export const options = [
  {
    name: "Tops",
    value: "top",
  },
  {
    name: "Bottoms",
    value: "bottom",
  },
];

export const createOption = (label) => ({
  label,
  value: label.toLowerCase().replace(/\W/g, ""),
});

export const colors = [
  createOption("Alice Blue"),
  createOption("Amaranth"),
  createOption("Amethyst"),
  createOption("Aquamarine"),
  createOption("Azure"),
  createOption("Beige"),
  createOption("Bisque"),
  createOption("Black"),
  createOption("Blue"),
  createOption("Bronze"),
  createOption("Brown"),
  createOption("Burgundy"),
  createOption("Burnt Sienna"),
  createOption("Byzantium"),
  createOption("Celadon"),
  createOption("Cerulean"),
  createOption("Cerulean Blue"),
  createOption("Champagne"),
  createOption("Chartreuse"),
  createOption("Chocolate"),
  createOption("Cobalt"),
  createOption("Coral"),
  createOption("Coral Pink"),
  createOption("Cornflower"),
  createOption("Cornsilk"),
  createOption("Crimson"),
  createOption("Crimson Red"),
  createOption("Cyan"),
  createOption("Dark Goldenrod"),
  createOption("Dark Green"),
  createOption("Dark Olive Green"),
  createOption("Dark Salmon"),
  createOption("Dark Slate Gray"),
  createOption("Deep Pink"),
  createOption("Deep Purple"),
  createOption("Deep Sky Blue"),
  createOption("Denim"),
  createOption("Eggplant"),
  createOption("Eggshell"),
  createOption("Emerald"),
  createOption("Firebrick"),
  createOption("Forest Green"),
  createOption("Fuchsia"),
  createOption("Gold"),
  createOption("Golden Yellow"),
  createOption("Goldenrod"),
  createOption("Gray"),
  createOption("Green"),
  createOption("Honeydew"),
  createOption("Hot Pink"),
  createOption("Iris"),
  createOption("Ivory"),
  createOption("Jade"),
  createOption("Jasmine"),
  createOption("Khaki"),
  createOption("Lavender"),
  createOption("Lavender Blush"),
  createOption("Lavender Gray"),
  createOption("Lemon"),
  createOption("Light Blue"),
  createOption("Light Coral"),
  createOption("Light Green"),
  createOption("Light Pink"),
  createOption("Light Slate Gray"),
  createOption("Lime"),
  createOption("Magenta"),
  createOption("Magenta Pink"),
  createOption("Magenta Rose"),
  createOption("Maroon"),
  createOption("Mauve"),
  createOption("Mauve Taupe"),
  createOption("Medium Purple"),
  createOption("Medium Spring Green"),
  createOption("Medium Turquoise"),
  createOption("Medium Violet Red"),
  createOption("Midnight Blue"),
  createOption("Mint"),
  createOption("Mulberry"),
  createOption("Mustard"),
  createOption("Navy"),
  createOption("Navajo White"),
  createOption("Neon Green"),
  createOption("Ocean Blue"),
  createOption("Olive"),
  createOption("Olive Drab"),
  createOption("Orange"),
  createOption("Orchid"),
  createOption("Pale Goldenrod"),
  createOption("Pale Green"),
  createOption("Pale Pink"),
  createOption("Pale Turquoise"),
  createOption("Papaya Whip"),
  createOption("Peach"),
  createOption("Peach Puff"),
  createOption("Pear"),
  createOption("Pearl"),
  createOption("Periwinkle"),
  createOption("Pink"),
  createOption("Platinum"),
  createOption("Plum"),
  createOption("Poppy Red"),
  createOption("Powder Blue"),
  createOption("Powder Pink"),
  createOption("Purple"),
  createOption("Raspberry"),
  createOption("Red"),
  createOption("Rose"),
  createOption("Royal Blue"),
  createOption("Ruby"),
  createOption("Sage Green"),
  createOption("Salmon"),
  createOption("Sangria"),
  createOption("Sapphire"),
  createOption("Scarlet"),
  createOption("Sea Green"),
  createOption("Seafoam Green"),
  createOption("Sienna"),
  createOption("Silver"),
  createOption("Slate"),
  createOption("Slate Gray"),
  createOption("Spring Green"),
  createOption("Steel Blue"),
  createOption("Sunflower Yellow"),
  createOption("Tan"),
  createOption("Tangerine"),
  createOption("Taupe"),
  createOption("Teal"),
  createOption("Terra Cotta"),
  createOption("Thistle"),
  createOption("Tomato"),
  createOption("Turquoise"),
  createOption("Ultramarine"),
  createOption("Vanilla"),
  createOption("Violet"),
  createOption("Viridian"),
  createOption("Wine"),
  createOption("Wine Red"),
  createOption("White"),
  createOption("Yellow"),

  createOption("Zaffre"),
];
